language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  # Install the *latest* Alien::TinyCC. This requires some trickery.
  - mv .git foo
  - mkdir alien-tcc
  - git clone git://github.com/run4flat/Alien-TinyCC.git
  - cd Alien-TinyCC
  - git submodule update --init
  - cpanm --install --notest .
  - cd ..
  - rm -rf Alien-TinyCC
  - mv foo .git
  # OK, proceed with the rest of the installation
  - cpanm --installdeps --notest .
